
name: Run Replit App

on:
  workflow_dispatch:
    inputs:
      zip_codes:
        description: 'ZIP codes to analyze'
        required: true
        default: '90210'
      down_payment:
        description: 'Down payment percentage'
        required: true
        default: '15'

jobs:
  run-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Replit App
        run: |
          curl -X POST "${{ secrets.REPLIT_URL }}/analyze" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "zip_codes=${{ github.event.inputs.zip_codes }}&down_payment=${{ github.event.inputs.down_payment }}&interest_rate=6.5&loan_term=30&monthly_expenses=300&min_coc_return=5&min_cash_flow=100"
